# Generated by Django 5.2.14 on 2026-09-05 02:50

from django.db import migrations, models

import core.choices


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_remove_linktrace_is_masked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                blank=True,
                choices=core.choices.get_language_choices,
                default=None,
                help_text="The language in which the user wants to see the interface.",
                max_length=10,
                null=True,
                verbose_name="language",
            ),
        ),
    ]
