# Generated by Django 5.2.14 on 2026-09-12 23:05

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_documentchatshare_commenter"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerDocumentCreation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("owner_sub", models.CharField(max_length=255)),
                ("key", models.UUIDField()),
                ("request_hash", models.CharField(max_length=64)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="server_creation_receipts",
                        to="core.document",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner_sub", "key"),
                        name="unique_server_document_creation",
                    )
                ],
            },
        ),
    ]
